name: my_plot_way
description: My Plot Way - offline CRUD with roles
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  sqflite: ^2.4.0
  path: ^1.9.1
  path_provider: ^2.0.15
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
